name: deploy to lambda
on: [push]
jobs:

  deploy_source:
    name: deploy create request from
    runs-on: ubuntu-latest
    steps:
        - name: checkout source code
          uses: actions/checkout@v3
        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v37
        - name: List all changed files
          run: |
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo $file
            done
        - name: Build binary
          run: |
            cd settings && zip ../deployment.zip create.py && cd .. && zip deployment.zip utils/auth.py utils/secret_manager.py
        - name: default deploy
          uses: appleboy/lambda-action@v0.1.9
          with:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
            aws_region: ${{ secrets.AWS_REGION }}
            function_name: offshore_settings_create
            zip_file: deployment.zip
            handler: create.handler
            runtime: python3.9