name: deploy to lambda
on: [push]
jobs:

  deploy_source:
    name: deploy create request from
    runs-on: ubuntu-latest
    steps:
        - name: checkout source code
          uses: actions/checkout@v3
        - name: Build binary
          run: |
            zip deployment.zip settings/create.py utils/auth.py utils/secret_manager.py
        - name: default deploy
          uses: appleboy/lambda-action@v0.1.9
          with:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_region: ${{ secrets.AWS_REGION }}
            function_name: offshore_settings_create
            zip_file: deployment.zip
            handler: handler
            runtime: python3.9